### ISSUE TITLE
Dash studio screen not return to idle after game

### ISSUE THREAD

**Issue by Meekstaaa** [SHWotever/SimHub#562] opened 2020-05-06 18:51 UTC
Hi,

Just thought I'd post this. After leaving a session sometime it doesn't return to idle and just goes black. All that I can see in the logs is this:

> 

  | ERROR | Unhandled dispatcher errorSystem.NullReferenceException: Object reference not set to an instance of an object.   at SimHub.Plugins.OutputPlugins.GraphicalDash.EditorModel.<>c__DisplayClass127_0.<WatchForUpdates>b__0(Screen i)   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)   at SimHub.Plugins.OutputPlugins.GraphicalDash.EditorModel.WatchForUpdates()   at SimHub.Plugins.OutputPlugins.GraphicalDash.DashWindow.RefreshWorker_Tick(Object sender, EventArgs e)   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
-- | -- | --

[SimHub.log](https://github.com/SHWotever/SimHub/files/4588860/SimHub.log)

**Comment by SHWotever** [comment] 2020-05-08 12:07
I've tried a fix on the next version

I close it for now as it's a duplicate of #526

**Closed** 2020-05-08 12:08 UTC
Labels: DashStudio, bug, done
