### ISSUE TITLE
Bodyshakers troubleshooting / ShakeIt Bass Shakers

### ISSUE THREAD

**Issue by luismuku** [SHWotever/SimHub#496] opened 2020-02-25 22:53 UTC
I am having problems because of Shake It Bass Shakers utility. I read the troubleshooting guide and tried this:

-Close Antivirus.
-Update Simhub
-Change UDP port on Simhub and Dirt Rally 2.0
-Execute Simhub and Dirt Rally 2.0 as administrator.
-Connect to different USB ports.
-Debug mode and Higher process activity enabled
-Run the game without Simhub (all OK)
-Run the game with Simhub open but Shakers disconnected (all OK).

I have a ShakeIt pedals mod and a TM1638 display and no problems with them. Sometimes (not always) when I am in a race the game starts stuttering, I lose the sound and my bodyshakers go crazy and then stop and everything is normal again, and after a few seconds de bodyshakers return to work OK, but the problem happens again later. I realize that this happens in concrete parts of the track, so I don't know if the problem is my PC or what but I play everything in High or Ultra Settings without this bodyshakers, so I don't think my PC hardware is the problem. 

My PC is:
-I5 3550
-16gb RAM DDR3
-GTX 1060 6gb

My cockpit (a lot of USB devices so I use two 7 USB ports Hub):
-TS-PC
-Zero delay button box
-G29 pedals Leobodnar
-Logitech Attack 3 as a handbrake
-SHH Shifter
-Rumble pedals mod (ShakeIt pedals)
-TM1638 Display
-4 Bodyshakers BS-250 and a SMSL SA-98E 2x160W
 
I started having trouble with Dirt Rally 2.0, but it also happened on Assetto Corsa. When I close Simhub or when I remove the USB sound card where the SMSL SA-98E and the bodyshakers are connected. Ah, and I tried two different USB but the problem still remains. 

I don't know why is this happening so I decided to ask here to find a solution. Please help me D:

**Comment by SHWotever** [comment] 2020-02-26 06:01
Hi ! Could you join the simhub log files after this happens ?

At first sight it looks like a full CPU or GPU , or maybe some thermal throttling happening in the middle of the race. Could you monitor this ? (You can use afterburner or similar tools)
With the log files I will be able to check if something is visible on the simhub side.

Nicolas

**Comment by luismuku** [comment] 2020-02-27 16:22
> Hi ! Could you join the simhub log files after this happens ?
> 
> At first sight it looks like a full CPU or GPU , or maybe some thermal throttling happening in the middle of the race. Could you monitor this ? (You can use afterburner or similar tools)
> With the log files I will be able to check if something is visible on the simhub side.
> 
> Nicolas

First of all thank you for answer. I recorded the moment where the game crash so you can see. 
0-1:00 -> Bodyshakers ON
1:00-1:37-> I've retired USB sound card where Bodyshakers are connected (still using Simhub with two arduinos).

I've used afterburner as you said and I can see that CPU turns crazy in the exact moment when the Bodyshakers and the game crash. This is Simhub's log:

[Simhub error txt.txt](https://github.com/SHWotever/SimHub/files/4262676/Simhub.error.txt.txt)

**Comment by SHWotever** [comment] 2020-03-02 21:23
Hi ! From What I see in the logs there were no particular issues except timeouts and game disconnects probably due to the cpu being at 100%. I close it for new as you did not reproduced it. If it happens again do not hesitate to check which process is using the cpu in the task manager.

Nicolas

**Closed by SHWotever** 2020-03-02 21:23 UTC
Labels: Waiting for infos

**Comment by luismuku** [comment] 2020-03-05 14:37
Hello, after a few days I continue trying to find a solution because it was
still happening, and I think I found the problem, so I think about telling
you because someone else can have the same problem.

I'd disconnected and reconnected USBs, update and reinstall simhub, try
with different USB ports and different USB sound cards... And the problem
was the power supply of Bodyshakers. I've been playing yesterday and today
with no problem, playing different games, racing against a lot of IA cars
(to force CPU) and not a problem, everything is correct.

Thanks for yout support and hope you a have nice day!
