### ISSUE TITLE
Update to the latest ETS2/ATS Telemetry spec

### ISSUE THREAD

**Issue by sjdawson** [SHWotever/SimHub#1050] opened 2022-03-19 23:17 UTC
There's a couple of data points in the latest telemetry spec that would negate some in my plugin, but better to get the data natively than my somewhat butchered way of getting it. The ETS SDK lists the latest spec as v1.17.

**Comment by SHWotever** [comment] 2022-08-13 20:53
Hi ! I close it as a duplicate of https://github.com/SHWotever/SimHub/issues/951

**Closed by SHWotever** 2022-08-13 20:53 UTC
