### ISSUE TITLE
An error occured while loading plugin

### ISSUE THREAD

**Issue by htusa31** [SHWotever/SimHub#1491] opened 2023-12-15 15:58 UTC
When I click to load in, this error pops up. I can click ok, but it just brings up a blank Simhub page. 
I have to force close the program. I am tried a full uninstall, reinstall etc... 
Nothing seems to work.  Version V9.1.16
![image](https://github.com/SHWotever/SimHub/assets/153934246/c21ff754-2947-4679-84b0-53e773dcbd9b)

**Comment by SHWotever** [comment] 2023-12-15 16:01
Hi ! Could you provide the detailed as asked here ? 
https://github.com/SHWotever/SimHub/issues/new?assignees=&labels=triage&projects=&template=bug_report.md&title=

Best regards,
Nicolas

**Comment by SHWotever** [comment] 2023-12-15 16:30
Duplicate of #1492

**Closed by SHWotever** 2023-12-15 16:30 UTC
Labels: Waiting for infos, Issue template missing
