### ISSUE TITLE
Tyre temperatures inner vs outer PCARS 2

### ISSUE THREAD

**Issue by adfolfotregosa** [SHWotever/SimHub#393] opened 2019-08-15 15:11 UTC
Maybe I'm missing something but comparing in-game values vs simhub they are switched. Tyre temperature inner should be outer and outer should be inner at least in project cars 2. 

I'm playing with a nextion display and just caught it.

**Comment by SHWotever** [comment] 2020-08-25 07:58
Duplicate of #632

**Closed by SHWotever** 2020-08-25 07:58 UTC
