### ISSUE TITLE
[BUG] Re-Import / Update of Dashboards not working

### ISSUE THREAD

**Issue by FullPace** [SHWotever/SimHub#1269] opened 2023-04-01 08:57 UTC
In 8.3.3 re-importing  / updating of dashboards is broken. There's no confirmation that the dashboard was imported, the window just disappears and the  .simhubdashboard files don't get extracted. they live as dashboardname.zip in the dashtemplates folder.

**Comment by SHWotever** [comment] 2023-04-02 13:31
Hi ! I tested and I could not see the issue, could you join the log simhub log files after an import attempt so I can take a deeper look ?

**Comment by FullPace** [comment] 2023-04-03 06:09
I was able to reproduce it. Simhub log shows nothing at all. Here's a video of it
https://www.dropbox.com/s/255sxxaq48cff71/unknown_2023.04.03-08.05.mp4?dl=1

**Comment by SHWotever** [comment] 2023-04-03 07:18
Hum I tried a couple of times with exported then reimported templates, I also tried your latest racedepartment release, I wonder if the issue is not in the file itself(there are some extra work about fonts ) could you link the file so I can take a look ?

**Comment by SHWotever** [comment] 2023-04-03 07:32
Ah sorry, wrong clue, archive seems fine, looked twice I got lost in the video, sorry :D . So the file should help.

**Comment by FullPace** [comment] 2023-04-03 07:39
Here's a link to the file.

I just tested on my rig computer and there it works fine. The only difference I see is that on the work pc simhub folder is backuped via GDrive. Could this be related?

https://www.dropbox.com/s/j37rwqzfz45gwxb/Pacelogic%20Pro.simhubdash?dl=0

**Comment by SHWotever** [comment] 2023-04-03 07:45
Oh indeed Gdrive is a half real half virtual file system it could alter file manipulations indeed, installing a template overall is just a matter of decompressing in simhub/temp then moving this folder when you accept installation (after having the old template zipped if you are overwriting one)

**Comment by FullPace** [comment] 2023-04-03 07:48
oh no... 🙈  but that's an easy test. When I'm back home, I try to reimport with paused gdrive and see what happens.

**Comment by FullPace** [comment] 2023-04-08 12:06
I finally had time to test and when Gdrive is turned off it still happens. Since it only seems to affect me I don't think you need to invest more time into it. I will just unzip and copy folders over.

**Comment by SHWotever** [comment] 2023-04-12 09:25
Hi ! I tried to reproduce the issue using google drive. And indeed it's the cause, Simhub starts by deleting the folder before reimporting it, but apparently GDrive is blocking the deletion (even when the app is not running) If I delete the folder manually using explorer it works as intended, but as soon as the deletion is initiated by simhub it will get blocked.

I also tried to unsync the folder first, but it looks like it's still held and locked, I had to manually delete the folder once before it works again.

**Comment by FullPace** [comment] 2023-04-13 10:36
Hello again, thats good to know.

whats weird is. that on my rig pc, that doesn't have gdrive the simhub folder are several zip files in the dash templates folder too. Could these  be left over files from installation? since I always get the feedback that the dashboards were imported correctly.

**Comment by SHWotever** [comment] 2023-04-13 10:44
Zip files are just backups when you overwrite an existing dash, better safe than sorry :D

**Comment by FullPace** [comment] 2023-04-15 16:04
Ok 👍 
You can consider this solved then :)

**Closed** 2023-04-24 10:11 UTC
Labels: Waiting for infos
