### ISSUE TITLE
Replay gain level different to live driving (shake it)

### ISSUE THREAD

**Issue by Mistermoleymole** [SHWotever/SimHub#1607] opened 2024-05-05 17:54 UTC
**Describe the bug**
When attempting to tune shake it fx/profiles the replay system is a great great option, however its difficult to get things right as the gain difference between driving live, and a recorded replay seems completely different.

**Simhub version**
Latest but been like this for a few versions now.

**To Reproduce**

Record a driven lap or few, then watch that replay back and see how shakers are far more powerful with their output when watching the replay.

**Expected behavior**
Please could the gain levels match for both live and replays, or advise if there is something I can do in the software or configs that can make them match.

**Screenshots**
NA

**Log files**
NA

**Additional context**
NA

**Comment by SHWotever** [comment] 2024-05-05 18:49
I close this as duplicate of those one :

https://github.com/SHWotever/SimHub/issues/986

Overall the solution would be a rewrite of replays to include precise timestamps and slow them down in the same conditions as they was recorded.

Hi ! Overall the replay are not timed this explains why it can emphase some effect (an absolute displacement seen in a shorter time will generate an higher effect).

As a workaround please make sure to record your replays in optimal conditions (avoid 3rd party plugins which are often the primary cause of slowdown), enable high process priority in simhub so it's not slowed down by an heavy system load. this way both records and replays can match the target 60fps and minimize differences

**Closed by SHWotever** 2024-05-05 18:49 UTC
Labels: triage
