### ISSUE TITLE
unable to execute file: simhubWPF.exe

### ISSUE THREAD

**Issue by FamXgame** [SHWotever/SimHub#1729] opened 2024-10-17 17:52 UTC
**Describe the bug**

**Simhub version**
Make sure to run the latest version

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by FamXgame** [comment] 2024-10-17 17:53
while installing simhub. i get error 2 message

**Comment by FamXgame** [comment] 2024-10-17 17:57
unable to execute file: simhubWPF.exe  

create process failed; code 2

the system cant find the file specified

**Comment by SHWotever** [comment] 2024-10-17 18:59
Hi !
This looks like an antivirus false positive

Actually the new version has been submitted to windows defender false positives as usual, but have not been processed yet, you can read more about windows defender (and other antivirus) false positives issues here: https://github.com/SHWotever/SimHub/wiki/Antivirus-false-positives
Unfortunately new releases flagging is quite common now due to the reasons explained in the wiki articles I've linked.

In the wait you can download the older versions which already got cleared: https://github.com/SHWotever/SimHub/releases

Best regards,
Nicolas Guilbert

**Comment by SHWotever** [comment] 2024-10-17 18:59
duplicate of #1728

**Closed by SHWotever** 2024-10-17 18:59 UTC
Labels: triage
