### ISSUE TITLE
iRacing flags - Not updating properly

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#594] opened 2020-06-08 20:24 UTC
Hi.
I noticed the flags don't work correctly anymore with iRacing.
Sometime they don't update or get stuck.
I'm looking at Telemetry.SessionFlags or the recently added dedicated flag properties.
Bonne soirée :).

**Comment by Romainrob** [comment] 2020-07-06 13:20
Hi.
I haven't notice this issue in a little while.
Maybe iRacing fixed it, or maybe there was another cause.
I'm thinking, I had SimHub running really slow at points during testing (dipping in the 30 fps range). Could this has cause it it to miss some changes in the flag value? Like at a game reader level?
In any case feel free to close the ticket. I'll reopen it it it happens again.
Bonne journée et j'éspère que votre installation se passe bien.

**Comment by SHWotever** [comment] 2020-08-25 08:00
Hello ! No it won't miss any data (at least about that) it always uses the latest from the game, there is no "time" based code for this.
I close it for now, do not hesitate if somehow it shows again, in my case I couldn't reproduce it neither.

**Closed by SHWotever** 2020-08-25 08:00 UTC
