### ISSUE TITLE
UDP

### ISSUE THREAD

**Issue by ly200412** [SHWotever/SimHub#898] opened 2021-08-16 13:24 UTC
Hello, I would like to ask a technical question, how can I receive UDP data sent by other games.

For example, I'm playing gtav manualtransmission game module.

There is a UDP element function. But I don't know how to receive the data it sends. May I ask you something.

Or give some ideas on how to develop UDP functions. It can be linked with simhub
![Uploading QQ图片20210816212357.jpg…]()

**Comment by SHWotever** [comment] 2021-08-16 14:52
Hi ! It looks like the mod exports data as DIRT4 format on port 20777, so you have to select dirt 4 in simhub and make sure it's configured on 20777 port (which is the simhub default) if the data is emulated correctly this should work.

**Comment by SHWotever** [comment] 2021-08-19 07:06
Duplicate of https://github.com/SHWotever/SimHub/issues/905

**Closed by SHWotever** 2021-08-19 07:06 UTC
Labels: question, done
