### ISSUE TITLE
DashStudio LED integration bugs

### ISSUE THREAD

**Issue by Meekstaaa** [SHWotever/SimHub#557] opened 2020-05-05 11:34 UTC
Hi,

Just a few little bugs I've noticed with the Dash Studio LED integrator.

- When deleting all profiles it won't let you load any new profiles. You have to create a new profile first before import option becomes available.
- When closing the LED integrated settings page within dash studio it moves the focus back to the main SimHub program and not the dash studio editor.

Is there also a way of integrating an option to auto use whatever you have loaded into the RGB led page on the Arduino tab?

Thanks! :)

**Comment by SHWotever** [comment] 2020-05-05 12:40
Thnaks for the report ! 
I fixed the load profile issue ! About led editor closing I could not reproduce it, so I forced focus on the parent window (dash studio in this case) after closing

About using arduino settings, I won't add it for now, I'm trying to make sure each feature is properly isolated and the led editor was a part of this work. Before I had shared settings for nextion and arduino leds for instance, and it was causing lot of confusion. I really want to avoid recreating this spaghetti working mode ;)

**Comment by SHWotever** [comment] 2020-05-09 06:00
Fixed in the last beta ;)

**Closed by SHWotever** 2020-05-09 06:00 UTC
Labels: LEDitor, bug, done
