### ISSUE TITLE
Antivirus

### ISSUE THREAD

**Issue by OtxiMOU** [SHWotever/SimHub#1538] opened 2024-02-07 10:55 UTC
the antivirus detects it as suspicious.

and the installation is not complete

**Comment by SHWotever** [comment] 2024-02-07 11:02
Hi ! This is unfortunately a false positive. "Suspicious" is indeed a good term for once, , usually antiviruses uses much more alarming fakes virus names. 
Do not hesitate to report it to your antivirus

I take care of clearing false positives for defender when it happens for defender, or some antivirus allowing "non customers" false positives submissions

You can find all the scan logs here showing its perfectly safe : #1525 

Unfortunately false positives are an infinite fight, even the smallest innocent applications if freshly built can trigger the false positives, and after a few years of trying to understand why and how this happens I can confirm that there is no true pattern and it's how the antivirus works(new = suspicious) and it can't be avoided on my end.

I close it as duplicate of #1525

**Closed by SHWotever** 2024-02-07 11:02 UTC
Labels: triage
