### ISSUE TITLE
[Feature request]Rotation option for driver’s marks on map

### ISSUE THREAD

**Issue by CNhjx** [SHWotever/SimHub#1650] opened 2024-07-19 01:21 UTC
Hello Nicolas
I rotate the map 90° to get a better display. And the driver's marks are also rotated. I didn'tfind an option for rotation in the opponents and player module. Is it possible to add this feature?
![image](https://github.com/user-attachments/assets/d55bff4f-6b79-4f42-a613-a7ef44da280d)
![image](https://github.com/user-attachments/assets/92605e87-85c0-4751-a2b9-97e16523412d)

**Comment by SHWotever** [comment] 2024-07-22 13:01
I ! Thanks for the suggestion, I close this as duplicate of this one : https://github.com/SHWotever/SimHub/issues/1506

**Closed by SHWotever** 2024-07-22 13:01 UTC
Labels: duplicate, enhancement, DashStudio
