### ISSUE TITLE
Allow Dash Studio UI to rename dashboard folder

### ISSUE THREAD

**Issue by jessemillar** [SHWotever/SimHub#1548] opened 2024-02-15 17:35 UTC
I can change the title of a dashboard in Dashboard Properties but that doesn't change the folder name in DashTemplates. Can/should the UI rename the folder? Can I just rename the folder to whatever I want? Will that break things?

**Comment by SHWotever** [comment] 2024-02-15 17:38
Duplicate of https://github.com/SHWotever/SimHub/issues/1547

**Closed by SHWotever** 2024-02-15 17:38 UTC

**Comment by jessemillar** [comment] 2024-02-15 17:41
This was actually meant to ask about the dashboard folder, not widget names. If I have a dashboard called "Test Dashboard" in "DashTemplates/Test Dashboard," if I wanted to rename it do I just rename "DashTemplates/Test Dashboard" to "DashTemplates/New Dashboard Name"? Does anything break if I do that?
