### ISSUE TITLE
Log Errors

### ISSUE THREAD

**Issue by CristianoBesi** [SHWotever/SimHub#678] opened 2020-10-12 10:29 UTC
Hello again.

As we discussed on the topic https://github.com/SHWotever/SimHub/issues/675, apparently I have managed to remove the issue by changing the transformer (which was recently faulty and probably emitting EMIs).
So far so good and it seems to work.

Despite it, I keep getting errors in the log. Since I would love to solve and possibly learn something from it, my question is:

are such errors due to the code written into the Arduino (that, therefore, needs to be fixed) or is there something else that isn't working?

Thanks in advance, as always, for your precious job
[SimHub.log](https://github.com/SHWotever/SimHub/files/5364552/SimHub.log)

**Comment by SHWotever** [comment] 2020-10-12 11:57
Hi ! 

It's not code errors it's invalid formulas, as a safety measure formulas leading to errors are only parsed once every 30s to avoid CPU overhead,

for instance this formula seen in the log : if(changed(25,[DataCorePlugin.GameData.NewData.ABSLevel], true, false) is invalid because one parenthesis is missing, it should be if(changed(25,[DataCorePlugin.GameData.NewData.ABSLevel] **)** , true, false)
I see all the formulas errors follows the same pattern. I see other bad syntax variations, but they are all related to custom content.

Overall it's not a technical issue just traces of malformed user content formulas (dashs .... custom properties ...), it won't impact the correct Simhub work as long as it's not related to what you are using.

Nicolas

**Comment by CristianoBesi** [comment] 2020-10-12 13:02
In fact SimHUB still works perfectly. In order to get rid of the errors, I have to rewrite the code in the Arduino?

**Comment by SHWotever** [comment] 2020-10-12 13:30
The errors are not occurring in the arduino, no problems about that ;) . it's some content hosted on the simhub side. Probably some dash formulas which should be fixed to remove the errors. Usually when such formulas fails it will simply stay in the default state, I see TC related  indicators for instance so I guess it's an indicator which will never show, so the issue is not visible except if you know it's lacking on the display. However since these formulas are in the custom content added to your installation that's not something I can fix on my end.

Just for the clarification, most arduino/usbd480/nextion etc ... are just considered as a display medium, except very rare exceptions it never manipulates "game data" , all the display data are computed on the computer inside simhub and sent as simple text/display values to the various devices. That's why you will find the errors in the simhub log but it won't affect much the devices. That was an assumed direction so arduino fimware updates are reduced to the strict minimum and almost never needs to be updated.

**Comment by CristianoBesi** [comment] 2020-10-12 22:01
Thanks a lot once more

**Comment by CristianoBesi** [comment] 2020-10-19 20:45
OK. I ve changed the powersupply, changed usb wires, they double-checked the Arduino welding. The weel works but the issues start whenever I play on ACC.
I used the wheel on AC massively and everything worked smoothly

on ACC, after a while, I get this message

RROR - JoystickManager : Error during reading of ITR_SW SharpDX.SharpDXException: HRESULT: [0x8007001E], Module: [SharpDX.DirectInput], ApiCode: [DIERR_INPUTLOST/InputLost], Message: Impossibile leggere dal dispositivo specificato.

**Comment by SHWotever** [comment] 2020-10-19 21:06
Hi ! Actually that's another symptom of the same original issue. The log error means that the device disappeared from the system and is not available anymore, you probably have the usb sound when this happens. That's with no doubts an hardware issue.

Could you try to reduce the LEDs brightness to see if that helps ? It will reduce the current requirements if somehow the wiring is too weak some LEDs and display refresh at the same time can lead to power drop and make the Arduino restart. 

If that doesn't help, do not hesitate to take contact with the seller, if I correctly remember you told you bought it already made, the seller is responsible for such hardware defects and it's probably running a custom sketch that I can't troubleshoot in my end neither.

**Comment by CristianoBesi** [comment] 2020-10-19 22:21
I ve even tried with Simhub not running at all. 
I ve realized that only ACC gives such issues, as AC and F1 series work flawlessly.

Getting desperate :(

**Comment by CristianoBesi** [comment] 2020-10-21 20:52
Apparently, if ACC o SimHUB is in spectator mode, everything works fine. Played 50 mins in a row without getting any issue.

What does Spectator mode do? any kind of filter?

Anyway, I will be trying it further in the next days

**Comment by SHWotever** [comment] 2020-12-20 09:41
Hello ! I close it as it's an hardware issue.

**Closed by SHWotever** 2020-12-20 09:41 UTC
Labels: done, question
