### ISSUE TITLE
[Feature request] ShakeIt Bass Skakers : control CUSTOM EFFECT Volume using Ncalc Formula

### ISSUE THREAD

**Issue by g-prome** [SHWotever/SimHub#1477] opened 2023-12-05 08:30 UTC
**Is your feature request related to a problem? Please describe.**
In ShakeIt Bass Skakers: I'd like to be able to control the CUSTOM EFFECT volume using formulas. To be able to control frequency and volume separately.

**Describe the solution you'd like**
Use a new Ncalc field in addition of the Response Filter

**Describe alternatives you've considered**
All that is currently possible using the Ncalc field + response curve + input /output modes. But this does not allow independent control of frequency and amplitude.

**Additional context**
I use customs effects almost exclusively, which is very useful for generating vibrations based on telemetry data + physical modelling 👍

**Comment by SHWotever** [comment] 2023-12-05 08:47
Hi ! Thanks for the suggestion I close this as a duplicate of this one :
https://github.com/SHWotever/SimHub/issues/911

**Closed by SHWotever** 2023-12-05 08:47 UTC
Labels: duplicate

**Comment by sierses** [comment] 2023-12-11 17:15
https://github.com/SHWotever/SimHub/issues/1022#issuecomment-1347924016
This is a potential way to implement separate volume and frequency control using two sets of custom code blocks.

The current workaround I'm using is several effects set to specific volumes that activate based on the modulus of an integer property. This gives 32 volumes levels using 5 effects which works great for instantaneous effects like suspension.
The downside is that sine wave outputs are not synced, so there are sometimes quiet frequency/volume combinations in continuous effects like RPM. My workaround for that was splitting two highest volumes across pairs of effects, using a total of 7 effects for 32 volume levels.
Of course, the cost of this is the load of several more effects which wouldn't be necessary with custom code blocks for volume.

**Comment by g-prome** [comment] 2023-12-23 08:27
> [#1022 (comment)](https://github.com/SHWotever/SimHub/issues/1022#issuecomment-1347924016) This is a potential way to implement separate volume and frequency control using two sets of custom code blocks.
> 
> The current workaround I'm using is several effects set to specific volumes that activate based on the modulus of an integer property. This gives 32 volumes levels using 5 effects which works great for instantaneous effects like suspension. The downside is that sine wave outputs are not synced, so there are sometimes quiet frequency/volume combinations in continuous effects like RPM. My workaround for that was splitting two highest volumes across pairs of effects, using a total of 7 effects for 32 volume levels. Of course, the cost of this is the load of several more effects which wouldn't be necessary with custom code blocks for volume.

it's very clever to use 5 channels for 2^5 = 32 possibilities! 👍
but desynchronisation and complexity are too much of a penalty 😬
simhub has the potential to create realistic vibrations... main lack is volume control 😭

**Comment by g-prome** [comment] 2024-01-13 15:39
![image](https://github.com/SHWotever/SimHub/assets/5487071/8b04728d-3cfe-4663-80b3-6c174434c1df)

merci pour la dernière màj !
