### ISSUE TITLE
9.1.28 flagged as suspicious by ESET Nod32

### ISSUE THREAD

**Issue by excessnet** [SHWotever/SimHub#1534] opened 2024-02-01 03:31 UTC
**Describe the bug**
ESET Nod32 dosent seem to like 9.1.28, flaging as suspicious and deleting the file.

**Simhub version**
9.1.28

**Additional context**
Rolledback to 9.1.27 and it's all good. Tell me if you want me to provide more informations.

**Details from Nod32 (csv format)**
﻿Time;Scanner;Object type;Object;Detection;Action;User;Information;Hash;First seen here
2024-01-31 10:21:02 PM;Real-time file system protection;file;D:\Program Files (x86)\SimHub\SimHubWPF.exe;Suspicious Object;cleaned by deleting;NT AUTHORITY\LOCAL SERVICE;Event occurred during an attempt to access the file by the application: C:\Windows\System32\svchost.exe (3F64C98F22DA277A07CAB248C44C56EEDB796A81).;F4F9A1B7FC9671900CA12BD51C376B19EF66B6C0;2024-01-29 10:16:33 PM

**Comment by SHWotever** [comment] 2024-02-01 05:56
Hi ! This is unfortunately a false positive. "Suspicious" is indeed a good term for once, , usually antiviruses uses much more alarming fakes virus names. 
Do not hesitate to report it to eset (unfortunately only their customers can do it as they require screenshots of the detection.)

I take care of clearing false positives for defender when it happens for defender, or some antivirus allowing "non customers" false positives submissions, but unfortunately eset doesn't allow it :

You can find all the scan logs and instructions about to report it to eset here : 
https://github.com/SHWotever/SimHub/issues/1525#issuecomment-1913659915

Unfortunately false positives are an infinite fight, even the smallest innocent applications if freshly built can trigger the false positives, and after a few years of trying to understand why and how this happens I can confirm that there is no true pattern and it's how the antivirus works(new = suspicious) and it can't be avoided on my end.

I close it as duplicate of #1525

**Closed by SHWotever** 2024-02-01 05:56 UTC
Labels: triage
