### ISSUE TITLE
[Feature request] - UDP Relay - Receiver

### ISSUE THREAD

**Issue by SimRacer918** [SHWotever/SimHub#1529] opened 2024-01-29 18:07 UTC
Hey Nicolas,
I would like to have a Receiver tab in UDP Relay. The idea is to allow users to share data across different devices. An Example is during an endurance race on ACC when you are spectating you get very limited data output from the game. Only the player that is driving the car gets the full data output from the game. I would be nice to setup a data pool with your teammates to shares the data across different devices. 
Another example where this feature could be useful is troubleshooting or developing dashboard or other accessories. You could have a player driving in one location while another user gets the data and can use this information to make something like an LED profile.
Currently how I kind of get around this is by using SimHub browser. All my teammates have Port forwarded the 8888 UDP port. Using their Public IPS in combination with the port allows me to access their Simhub browser and run a dashboard. I would be nice to use their data directly through SimHub and therefore allow us to display different data on monitors or dashboard, etc.
I am not sure how the GT7 implementation works but I seems like it’s a similar idea where UDP game data is picked up by SimHub though the network and made accessible. I have used photoshop to make a UI to show you how I envision the Idea to be implemented and attached the photos below.
I have added conditions where you can enable and disable data Routing by using the property such as [DataCorePlugin.GameData.Spectating]. This way it should automatically switch data depending on which player is driving but everyone still gets the full data output when spectating which can be very handy for running Pitwalls for example. 

![Forward UI](https://github.com/SHWotever/SimHub/assets/98562742/fa4de7ad-35e8-4cd3-a9c3-11fe6d3e7b62)
![Receive UI](https://github.com/SHWotever/SimHub/assets/98562742/3f80736e-efd1-47bf-87e3-6cd285554935)

I have tried to look into making my own plugin but that’s a bit to farfetched for my limited coding abilities unfortunately. Regardless I hope you could implement this feature In the future of its possible. Thank you for creating an awesome platform that is constantly being developed, keep up the good work!

**Comment by SHWotever** [comment] 2024-01-29 18:53
Hi ! Structurally the relay can't receive game data. It has to be much higher in the "stack", However your example about ACC specifically is flawed because it's a composite (shared memory+ udp feed). For all games using basic data flow, it's possible to forward it natively in the game settings, and simhub will receive it (it's the case for GT7 for instance). But when it's not possible it's not available (like ACC composite API) 

The true solution would be to implement this : https://github.com/SHWotever/SimHub/issues/1411 , but i'm a little frisky about all the work required combined with the bandwidth and lag related (this had existed in the old SimHub versions (really old) and it was an heavy complex machinery with too few users).   

I cose this as a duplicate of #1411

**Closed** 2024-01-29 18:54 UTC
Labels: duplicate

**Comment by SimRacer918** [comment] 2024-01-29 20:04
Hey,

Thanks for the reply. I didn't know that it specifically worked that way. Thanks for the insight. Maybe the solution #1411 could be implemented in the future as an option that the user could enable with an apropriate warning?
