### ISSUE TITLE
Phone/Tablet dashboard buttons no longer work

### ISSUE THREAD

**Issue by SteveFurio** [SHWotever/SimHub#1259] opened 2023-03-26 02:58 UTC
**Describe the bug**

Today I updated from version 8.1.3 to 8.3.2. I can no longer get buttons to work on phone/tablet dashboards. They will work in dashboard testing and as a monitor overlay, just not on phones or tablets. I reverted back to 8.1.3 and they all worked again. 

**Simhub version**
Make sure to run the latest version

8.3.2 - They don't work
8.1.3 - They do work
* I have not tried any other versions

**To Reproduce**
1. Go to '....'

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**

**Comment by SHWotever** [comment] 2023-03-26 06:32
Hello ! Thanks for the report ;) I close it as duplicate of #1242

**Closed by SHWotever** 2023-03-26 06:32 UTC
