### ISSUE TITLE
Scaling track-map bug in Dash Studio

### ISSUE THREAD

**Issue by SimRacer918** [SHWotever/SimHub#1069] opened 2022-05-03 12:30 UTC
When trying to scale up the map parts of the track seem to disappear, as if there is a border around the the track as show in the attached pictures

To reproduce this bug either scale a track map in the Dash Studio or install the attached "SimHub dash file.zip", and I am running SimHub version: 7.4.22 

**Additional context**
![Track scaling](https://user-images.githubusercontent.com/98562742/166451859-c61dc75f-0416-4f84-90de-ebeae3e0ee82.png)
![Track scale cut](https://user-images.githubusercontent.com/98562742/166451869-f47195c2-d670-4b42-b805-e9398ff120c7.png)
[SimHub dash file.zip](https://github.com/SHWotever/SimHub/files/8610361/SimHub.dash.file.zip)

Thx for the amazing software!

**Comment by SHWotever** [comment] 2022-08-13 21:01
Hi ! I close this as a duplicate of https://github.com/SHWotever/SimHub/issues/832

**Closed by SHWotever** 2022-08-13 21:01 UTC
Labels: bug, DashStudio
