### ISSUE TITLE
Random Simhub telemetry crashes

### ISSUE THREAD

**Issue by thifremana87** [SHWotever/SimHub#1447] opened 2023-10-22 18:03 UTC
**Describe the bug**
Simhub telemetry randomly crash. Simhub still work (interface) but my 2 dashes, 2 bashakers and LED strips are "frozen". Once Simhub restarted, everything works properly.
In the attached log file, the crash occurred at 16:25.
I can read "Abnormal Inactivity detected" but I don't understand the other informations.
Sorry for my bad english.
Thanks in advance.

**Simhub version**
9.1.5

**Third party plugins**
No

**To Reproduce**
Randomly after a few minutes of driving (Rfactor2).

**Expected behavior**

**Screenshots**

**Log files**
[SimHub.5.txt](https://github.com/SHWotever/SimHub/files/13064111/SimHub.5.txt)

**Additional context**

**Comment by SHWotever** [comment] 2023-10-22 19:48
Hi ! 

Thanks for the log, apparently the remote phone or tablet stops responding and simhub get stuck "waiting" for it to accept the data. This could be a network,firewall/antivirus issue or the device itself not holding the dash. 

- Could you tell me which kind of device you are using as well as the android version? 
- Try do disable for a test your firewall (defender should not cause issues, but some other firewalls might be more random.

I see you are using the mobile app. If you don't have an up to date android app is constrained by the os version bugs. Switching to chrome will help in such case (chrome is up to date no matter the version of Android)

You can find a more complete list of advices here : 
https://github.com/SHWotever/SimHub/wiki/Troubleshoot-Dashstudio-Web-access#dash-is-lagging-or-randomly-disconnecting

**Comment by thifremana87** [comment] 2023-10-22 20:04
Hi,
First thanks a lot for your very fast answer.
I'm using an old Android phone (Honor 7) with an old Android version and
the v3 Simhub app. I used to use chrome but I switched to the app a few
weeks ago.
I will try with chrome and will get you updated.
Thanks so much.

**Comment by thifremana87** [comment] 2023-10-25 17:58
Hi,
I had a new crash today. Simhub froze suddenly : 2 dashs froye, same for LED strip (with Arduino), and bass shakers stopped with a sort of white noise.
Same devices :
- Honor 7 (Android 6.0) with Chrome
- tablet Galaxy Tab A Android 7+ with Chrome too.
Game : rFactor 2
See log attached.

[trace_2023_10_25_17_40_48-25.txt](https://github.com/SHWotever/SimHub/files/13169165/trace_2023_10_25_17_40_48-25.txt)
Thanks in advance.
Regards.

**Comment by SHWotever** [comment] 2023-10-25 18:03
Hi ! Unfortunately this is the rf2 log,I need the simhtlog like the one you joined the first time.

Have you tried the other advices from the liti linked previously? 


> You can find a more complete list of advices here : https://github.com/SHWotever/SimHub/wiki/Troubleshoot-Dashstudio-Web-access#dash-is-lagging-or-randomly-disconnecting

**Comment by thifremana87** [comment] 2023-10-25 18:18
what an idiot !!! Désolé, sorry!

Here is the Simhub log file :
[SimHub.txt](https://github.com/SHWotever/SimHub/files/13169295/SimHub.txt)
It happened around 19:49.
Maybe it's the Arduino's fault (EMIs?) that could cause wifi disconnections of the phone. The LEd Strip is just in front of the phone.

And yes, I cheked all the advices except the rendering speed at this day.
Thanks again.

**Comment by SHWotever** [comment] 2023-10-25 19:02
Thanks, I can see the issue is again on the same place, it got stuck when sending data to one of the "html' devices (phone or tablet)

There is one of those two which gets unreachable or is freezing.

In the incoming version I've made web devices updates asynchronous, it won't "fix" the root cause (wifi, device, os ?) but it will help constrain it to the faulty device (or devices in case of network issue) and keep remaining features alive. 

Here is a link to the beta :  https://simhubdash.com/unofficial/SimHub.9.01.6b5.zip

**Comment by thifremana87** [comment] 2023-10-25 19:08
Waouw, thanks again for your VERY fast expertise. This is very interesting.
I will test this beta and will get you updated.
You're the Best.
Regards.
Merciiiiiii.

**Comment by thifremana87** [comment] 2023-10-27 16:01
Hey Wotever,
I changed my Android device with an "up to date" one.
I didn't have a crach but I think that I still have the same error in logs (see attached).
[SimHub.txt](https://github.com/SHWotever/SimHub/files/13191039/SimHub.txt)

Could you confirm please ?
Thanks
Regards

**Comment by SHWotever** [comment] 2023-10-27 16:31
I can't see the watchdog hitting anymore, there is nothing stuck now (the watchdog is a little helper watching for freezes and logging everything running at this time, it's super efficient to spot any guilty events like in your first logs).

For the remaining errors, you have the "debug" logging activated in settings which catches any errors even the "handled" errors including internal libraries errors. This can be handy for advanced troubleshooting but it's also a little confusing. The logs simply shows some network activity but nothing faulty from my point of view, it's not abnormal for a webserver to keep a connection open and close it later (IE keep alive mechanic : https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive).

You can disable those logs here : 
![image](https://github.com/SHWotever/SimHub/assets/2207331/d84b3569-15fc-4fec-a00e-8e80219823d8)

**Closed** 2023-10-30 05:30 UTC
Labels: Waiting for infos
