### ISSUE TITLE
SimHub not working

### ISSUE THREAD

**Issue by BeanzSK** [SHWotever/SimHub#1686] opened 2024-09-07 19:57 UTC
I have no troubles with installation but when i want to run the app it opens it asks me those thing like if i want mph or kmh when i click ok and its done i cant click anything else and if i click app icon on taskbar it just crashes and shows its still running in task manager i tried reinstalling deleting files and other stuff but nothing of those things worked 
i have the newest 9.4.5 version

**Comment by SHWotever** [comment] 2024-09-07 20:04
Hi ! Could you install the latest version ? https://www.simhubdash.com/download-2/  9.4.5 had an issue with fresh installations indeed.

**Comment by SHWotever** [comment] 2024-09-07 20:19
Closing as duplicate of #1687

**Closed by SHWotever** 2024-09-07 20:19 UTC
Labels: question, done

**Comment by BeanzSK** [comment] 2024-09-08 10:32
thx very much everything is working now
