### ISSUE TITLE
Govee lighting has three-second lag (three-second polling rate)

### ISSUE THREAD

**Issue by HoonyTunes** [SHWotever/SimHub#1702] opened 2024-09-17 08:27 UTC
**Describe the bug**
Three-second delay in colour change for Govee lights. Lights have no lag if closing SimHub and launching the Govee lighting app instead to do the same job (read screen, match colours), so it is definitely a SimHub issue. 

By moving windows into capture zone, I have measured the lag at around 3 seconds. However, if you wait two and a half seconds, then change the colour in the capture area, it takes half a second to change. I have determined that it must therefore be that SImHub is polling at a rate of between once every two or three seconds. I cannot find any setting that may be making the polloing rate so slow. 

This also manifests when testing blinking yellow red flags for example, where the lights turn solid yellow after up to three seconds, and then don't blink, but turn full off for a while, then full on again for a while, indicating the polling is sometimes hitting during the blink on phase and sometimes hitting in the blink off phase.

**Simhub version**
Yes, I am running the latest version

**Third party plugins**
No third-party plugins running

**To Reproduce**
Once the lights are connected and set up correctly, just move some coloured windows in our out of the capture area to see the extraordinary lag.

**Expected behavior**
The lights should change instantaneously to match approximation of colours in the capture area. They do not.

**Screenshots**
N/A

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).
[SimHub.6.txt](https://github.com/user-attachments/files/17025144/SimHub.6.txt)
[SimHub.5.txt](https://github.com/user-attachments/files/17025145/SimHub.5.txt)
[SimHub.4.txt](https://github.com/user-attachments/files/17025146/SimHub.4.txt)
[SimHub.3.txt](https://github.com/user-attachments/files/17025147/SimHub.3.txt)
[SimHub.1.txt](https://github.com/user-attachments/files/17025148/SimHub.1.txt)
[SimHub.2.txt](https://github.com/user-attachments/files/17025149/SimHub.2.txt)

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by HoonyTunes** [comment] 2024-09-17 14:40
Sure, the H6065 and the H6065 are the only two lights I have set to run with SImHub. The H6110 is also on the network as it has LAN control, but not added to SimHub, so very odd the logs would mention it.

**Comment by HoonyTunes** [comment] 2024-09-17 14:50
Done, see above.

**Comment by SHWotever** [comment] 2024-09-17 14:58
Thanks ! That's giving me some insights ! overall on H6065 the colors are showing but very slowly, right ? I see where it could wait for a long time but I would need to confirm that behaviour. Overall it wais for the device confirmation for around 3s that razer mode is enabled before sending the color, if there is no reply it will send the color anyway, but the next time it will have to do it again as razer mode is still not confirmed.

**Comment by HoonyTunes** [comment] 2024-09-17 15:14
Yes, that's the behaviour. It's changing colours, to the correct colours, but with a huge delay.

**Comment by SHWotever** [comment] 2024-09-17 15:27
Could you try this version ? https://simhubdash.com/unofficial/SimHub.9.04.8b1_GoveeNoReply.zip
If the device does not reply correctly about its status it should now avoid this lengthy wait between each update. But as long as it accepts the commands (which seems to be the case) it should work.

**Comment by HoonyTunes** [comment] 2024-09-17 15:48
Yes, this works!!! Thank you? Will future updates contain this edit?

**Comment by SHWotever** [comment] 2024-09-17 19:15
Thanks for the feedback, I tested this "fix" deeper and it had lot of bad side effects about start and stop since the status was not properly synchronized. 

I've investigated deeper in the original govee app and I found that the "status" message could be longer than before and so it could be 'missed', but it was probably not 'missing'.

I've build a new version closer to the original which properly waits for the status update, but handling those longer status messages. This SKU was probably victim of this longer message.

Could you test it and tell me ? 
https://simhubdash.com/unofficial/SimHub.9.04.8b2_GoveeNoReply.zip

If this works it will be remove the bad side effects and it could take its way to the next release.

NB : I've also improved multiple network cards support, properly scanning for govee devices over all networks instead of the default one (which could be the wrong one depending of windows network "mood"), it's an issue which is also still occurring in govee original app)

**Comment by HoonyTunes** [comment] 2024-09-18 06:52
No problem. I'll test next time I fire up the sim rig later this morning and let you know.

**Comment by HoonyTunes** [comment] 2024-09-18 13:06
Okay, that is SUPER-responsive now! Thanks so much. I also added another Govee light today, a 5m H61A2, and it works great now too. No perceivable lag!

**Comment by SHWotever** [comment] 2024-09-18 17:46
Hi thanks a lot for your feedback ! Happy to hear that this "cleaner" fix did the trick. It will be released with the next update.

Nicolas

**Closed by SHWotever** 2024-09-18 17:46 UTC
Labels: Waiting for infos
