### ISSUE TITLE
virus alert

### ISSUE THREAD

**Issue by beregor** [SHWotever/SimHub#1334] opened 2023-06-16 20:52 UTC
**Describe the bug**
when downloading zip file from webpage i get virus alert

**Simhub version**
N/A

**To Reproduce**
Microsoft defender and download from webpage

**Expected behavior**
it shouldent get warning for virus

**Screenshots**

![image](https://github.com/SHWotever/SimHub/assets/74149627/7edb5343-dc14-4974-91c6-3ba729ea4ac1)

![image](https://github.com/SHWotever/SimHub/assets/74149627/92e7e149-d6b8-427b-a18a-cb73ed1182fe)

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**

**Comment by SHWotever** [comment] 2023-06-16 22:17
Hi ! This is a false positive from windows defender, you can check the installer scan here : https://www.virustotal.com/gui/file/3baba8bd74a5c07f527760fdaa15abe186a801d28a7ee76e9d929285d3ddb03d

I'm reporting it to Microsoft so they fix it, it usually takes a few hours.

**Comment by SHWotever** [comment] 2023-06-16 22:18
Duplicate of #1333

**Closed** 2023-06-16 22:25 UTC
Labels: duplicate
