### ISSUE TITLE
Wheres 8th Gear

### ISSUE THREAD

**Issue by Dreese001** [SHWotever/SimHub#1235] opened 2023-02-25 02:06 UTC
**Describe the bug**
Ultimate Gen2 Car in AMS2 has 8 gears
Attached is RAW data showing the car has MAX 8 gears, but the Dashboards only register 7 gears. When I change to 8th gear - it shows as 7th Gear again (so there's 2 x 7th Gears). When I'm in 8th gear, I shift down gears 3 x times to get to 5th Gear, however 8th gear is showing as a 2nd 7th gear

**Simhub version**
8.2.2

**To Reproduce**
Start AMS2 using Ultimate Gen2 car

**Expected behavior**
When selecting 8th Gear, then the Dashboard should show 8th gear

**Screenshots**
see attached

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**
I dont know any other cars using 8 gears

![Wheres 8th Gear](https://user-images.githubusercontent.com/116535622/221330368-08633463-5685-49d3-a31b-96a10f21da53.png)

[SimHub.log](https://github.com/SHWotever/SimHub/files/10830053/SimHub.log)

**Comment by SHWotever** [comment] 2023-02-25 09:30
Hi !

I checked and I could not reproduce the issue on shared memory version , I got the 8th gear as expected on the Shared memory telemetry :
![image](https://user-images.githubusercontent.com/2207331/221349045-75f2afef-ef7c-40be-baa9-67790d888f2e.png)

![image](https://user-images.githubusercontent.com/2207331/221349077-e843fbe0-c2a8-4a24-97a8-c3a51922d26c.png)

That said the UDP telemetry is buggy from the game :
The gear data is stored in DataCorePlugin.GameRawData.sTelemetryData.sGearNumGears coming straight from the game, if you change gear you will see it change (ignore the final value as both maxgears and current gear are packed in the same byte, just focus on value change) from R to 7 then get stuck from 7 to 8, the 8th gear is not reported by the game and appears as a 7th gear.

In such case the best will be to switch back to Shared memory, it's much more efficient and does not has this bug. UDP was filling a few lacks of tyre temps, but the AMS2 team has filled the gap now.

Unfortunatelty it's something which must be fixed in the game itself. The structure can hold up to 15 gears when fixed in AMS2 it will work as intended.

**Closed** 2023-02-27 10:22 UTC
Labels: done, technical limitation

**Comment by Dreese001** [comment] 2023-03-05 03:13
Hi Team

Are these Shared Memory Settings correct for me to be able to display 8th
Gear? - see attached
As far as I know, I need these settings for Sim Racing Studios to
interpret the telemetry for my DOF Motion Platform - please let me know if
its wrong.


Kind Regards

Dreese Kapa
Auckland, New Zealand
