### ISSUE TITLE
SimHub process will not terminate after opening BeamNg.drive

### ISSUE THREAD

**Issue by MrArgon39** [SHWotever/SimHub#1423] opened 2023-09-24 11:42 UTC
**Describe the bug**
After opening BeamNg with SimHub open, and using the extended telemetry script, SimHub will no longer terminate, nor will it allow you to switch games.

**Simhub version**
Version 9.0.4

**Third-party plugins**
No third-party plugins are installed

**To Reproduce**
Steps to reproduce the behaviour:
1. Open SimHub and select BeamNg
2. Open BeamNG
3. Close BeamNG
4. Attempt to close SimHub, or change the selected game
5. SimHub will fail to terminate all processes or will lock up when trying to switch.

**Expected behaviour**
I expected SimHub to close, or to allow me to switch games.

**Screenshots**
Attempting to Select DiRT 4 with SimHub in the broken state
![broken](https://github.com/SHWotever/SimHub/assets/62647685/b6156117-68cf-47dd-9c34-e8d94983019c)

**Log files**
Previous Two Logs
[SimHub.txt](https://github.com/SHWotever/SimHub/files/12708401/SimHub.txt)
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/12708402/SimHub.1.txt)

How to attach files: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**
Sometimes a weird car name appears in the per-car overrides, no idea if related.

**Comment by SHWotever** [comment] 2023-09-24 13:36
Hi ! Indeed your intuiation about this weird car name is the cause, do you have an idea of what you did to make it appear ? I will fix the saving for this weird car, but it would be better to fix the original cause.

**Comment by MrArgon39** [comment] 2023-09-24 21:35
From a bit of tinkering I did with Wireshark a little after posting the issue, I believe that my WiFi router and repeater have some sort of communication on UDP port 9999, so I think that that may be causing it.
When I get back home I will be able to provide some more information.
Thanks

**Comment by MrArgon39** [comment] 2023-09-25 10:36
After further tinkering, the usage of UDP port 9999 seems to be the root cause of the phantom vehicles, as when the router and repeater communicate, they do so over port 9999. Manually editing the Lua script to use a different port seems to fix the issue.

**Comment by SHWotever** [comment] 2023-09-26 13:27
Ok cool ! Otherwise you can configure the port straight in SimHub, the "automatic configuration" will take care to put in the game settings (it requires a game restart)

I close this as the issue was caused by an external factor.

**Closed** 2023-09-26 13:31 UTC
Labels: done
