### ISSUE TITLE
Sim hub does not control default sound output anymore

### ISSUE THREAD

**Issue by beastlyfern** [SHWotever/SimHub#1616] opened 2024-05-18 01:17 UTC
I am using the most up-to-date version of sim hub on widows 11 but no matter what I do it will only adjust the levels of my soundcard which is not set to be any of the windows default audio settings.  The default audio is and always has been set to my usb headphone dac and up until a couple weeks ago simhub would control the default audio device but no no matter what I do it will only adjust the Realtek usb speakers output not the default audio setting of speakers 3 resonessence labs concero hd.

Thanks for any help with this and the amazing program.

<img width="793" alt="audiio" src="https://github.com/SHWotever/SimHub/assets/87458747/aac71189-b7f5-4e74-827c-2aeb41f2d288">
<img width="529" alt="Screenshot 2024-05-17 191512" src="https://github.com/SHWotever/SimHub/assets/87458747/67ddaa38-0be4-4d97-a31f-bb0aded268c7">

**Comment by SHWotever** [comment] 2024-05-18 06:59
Hi ! This is a duplicate of : https://github.com/SHWotever/SimHub/issues/1610#event-12854254496

**Closed by SHWotever** 2024-05-18 06:59 UTC
Labels: duplicate, triage
