### ISSUE TITLE
ACCv1.0.7.1 heavy cpu usage

### ISSUE THREAD

**Issue by EAKMotorsports** [SHWotever/SimHub#404] opened 2019-09-09 18:33 UTC
Well with the 6.8.3 and 6.8.4 versions I getting an very high cpy usage even on desktop ( i mean I just open the SimHUB and i getting more that 90% of cpu use only on Simhub.
the 6.8.2 was okay very low cpu usage
[SimHub.log](https://github.com/SHWotever/SimHub/files/3592041/SimHub.log)

-ACC v1.0.7.1
-SimHUB 6.8.3 - 6.8.4 (6.8.2 was okay very low cpu usage)
-no Arduino. SimHUB Android app (Samsung Galaxy Tab 10.1 2014 edition), 7" hdmi LCD, iOS browser (iPhone SE 64GB). Not simultaneous use. I mean sometimes I use the tablet other the 7" display others the smartphone but never all together.
-too bad the delta not work on online races. (funny fact, race game with out lap time/delta doesn't make too much sense. I know its wasn't ur fault its "kunos" fault)

**Comment by SHWotever** [comment] 2019-09-09 18:42
Hi !

I see an error loop coming from the EnsiFerrum_ACC plugin, this such error loop will create huge CPU load indeed you can disable it in simhub settings time for the author to update it.

Nicolas

**Comment by SHWotever** [comment] 2019-09-09 18:46
About delta I know it will be solved soon, they are progressively enhancing the telemetry. Hopefully, as soon as it will be released we will finally have a "full featured" telemetry.

**Comment by Ensi-Ferrum** [comment] 2019-09-09 19:35
As soon as V1.0.8 of ACC is released I will post an update of ACC-CDS.
But I must warn you: As I am doing a big overhaul of all the dashes maybe not all will be working.

**Comment by EAKMotorsports** [comment] 2019-09-09 20:06
> 
> 
> Hi !
> 
> I see an error loop coming from the EnsiFerrum_ACC plugin, this such error loop will create huge CPU load indeed you can disable it in simhub settings time for the author to update it.
> 
> Nicolas

Well I disable it and still with high cpu load.

[SimHub.log](https://github.com/SHWotever/SimHub/files/3592387/SimHub.log)

**Comment by SHWotever** [comment] 2019-09-09 20:27
Strange. Does it happen when another game is selected or is it specific to ACC? 
Could you enable the "debug mode" in setting, restart SimHub and grab some fresh logs?

**Comment by EAKMotorsports** [comment] 2019-09-09 21:56
[SimHub.log](https://github.com/SHWotever/SimHub/files/3592755/SimHub.log)

On desktop not even in the game.

**Comment by EAKMotorsports** [comment] 2019-09-16 22:53
todays update   
[SimHub.log](https://github.com/SHWotever/SimHub/files/3618511/SimHub.log)

**Comment by SHWotever** [comment] 2019-09-16 23:13
Hi!

Sadly the logs did not give me clues for now,
did you had a chance to test with another game activated (even if you are not running the game)
It will help to know if it's something related to the game reader itself or something else.

I don't know if you can do that, but getting a zip of the whole simhub install folder could help too.
If you could make a zip (or a rar) and upload it to some site like https://www.mediafire.com/ or https://mega.nz/ I hope it will help to locate what is triggering this abnormal consumption.

**Comment by EAKMotorsports** [comment] 2019-09-16 23:32
well I tried with AC and SimHUB if fine 0.6-1.6%.

**Comment by EAKMotorsports** [comment] 2019-09-17 00:07
here is the link with my SimHUB https://drive.google.com/open?id=1zXfICMWAaYAmpfs1rP119xNM1psGrB81

**Comment by EAKMotorsports** [comment] 2019-09-17 03:31
here is the link with my SimHUB https://drive.google.com/open?id=1zXfICMWAaYAmpfs1rP119xNM1psGrB81

**Comment by EAKMotorsports** [comment] 2019-09-17 03:31
here is the link with my SimHUB https://drive.google.com/open?id=1zXfICMWAaYAmpfs1rP119xNM1psGrB81

**Comment by EAKMotorsports** [comment] 2019-09-18 18:01
I give the access to dw.

**Comment by SHWotever** [comment] 2019-09-18 18:26
Hi ! Thanks ! Sadly I tried two or three times to download the file (with two different browser) but it ended corrupted each time, Are you sure the upload was successful ?

In the wait based on the info that it only occurs on ACC i'm trying to dig to see if some conditions which could trigger that, that's still a very good clue.

**Comment by EAKMotorsports** [comment] 2019-09-19 05:54
http://www.mediafire.com/file/byrwee85r2ja9si/SimHub.7z/file

**Comment by SHWotever** [comment] 2019-09-19 19:20
Hi ! 
Sadly the file was corrupted too,

I tried to follow my clues based on the fact that it was ACC specific, I've built a version where i've made some changes to the ACC broadcasting SDK (used to grab opponents data), I could not reproduce anything but I feel that in some specific conditions it could be an issue.
https://www.simhubdash.com/unofficial/HubPackage.6.08.7b.zip

I've also added a setting to totally disable it if somehow it still max up CPU, I would be interesting to try to disable it so I will be sure it comes from the broadcasting SDK. To disable it you have to open the simhubwpf.config file (stored in c:\Program Files (x86)\SimHub\) with notepad  and change the following line : 
![image](https://user-images.githubusercontent.com/2207331/65274146-f8242480-db22-11e9-9b50-8fb66c873653.png)
Set it to false, and restart SimHub.

Let me know if the changes solved it, or in the bad case if disabling broadcast API helped.

**Comment by EAKMotorsports** [comment] 2019-09-19 23:19
http://www.mediafire.com/file/odcjowa6h0rtq3e/SimHub.7z/file   Well I made another zip and upload, sry for the trouble. Now I gonna try the 6.08.7b to see the difference. thx for that.

**Comment by EAKMotorsports** [comment] 2019-09-20 18:05
Well I did some testes and the problem for me is the EnsiFerrum dashs when I select that dash, the cpu gotta crazy. But when I use others dashs the cpu is fine. Something in the new ACC update+EnsiDah+SimHUB (after 6.8.2 update) gets my cpu crazy. I did the thing about disabling broadcast API, helped an little the cpu got less work but still high. thx for your help. keep up the great work I really love it.

**Comment by Ensi-Ferrum** [comment] 2019-09-20 20:17
@EAKMotorsports 
Are there any other *.dll's starting with EnsiFerrum in your SimHub directory than these 4?
![image](https://user-images.githubusercontent.com/2466941/65356278-57059e80-dbf4-11e9-8155-9bcf2289bd4c.png)
If yes: Delete them.

**Comment by EAKMotorsports** [comment] 2019-09-20 20:35
no, only those.

**Comment by SHWotever** [comment] 2019-09-21 07:56
Hi!

The new download was correct, and allowed me to find instantly what was going on! Honnestly I would have never guessed it without.

You have a "UDP relay" from 9000 to 9000 basically triggering an infinite loop (receiving data from gamereader, sending it to 9000, received by the relay, sent to 9000, received by the relay, etc .. etc ... 
 I've added a fix to avoid such a situation in the next version. In the wait you can simply remove this relay, Simhub will cool down instantly : 
![image](https://user-images.githubusercontent.com/2207331/65370153-ff981a80-dc55-11e9-88aa-a6c887d8f603.png)

**Comment by EAKMotorsports** [comment] 2019-09-25 03:44
Well I did some tests and the problem is gone.. Thank you very much for your help. and keep up the great work.

**Comment by SHWotever** [comment] 2019-09-25 05:18
Nice ! Happy to hear it !

Nicolas

**Closed by SHWotever** 2019-09-25 05:18 UTC
Labels: Done, bug, question
