### ISSUE TITLE
System Monitor errors

### ISSUE THREAD

**Issue by rifer1** [SHWotever/SimHub#801] opened 2021-04-21 18:49 UTC
My Sys Monitoring Configuration displays incorrect name for two of my selected parameters.  Photo and log attached.  Note the last two.

All I can alter is the right hand column; in some instances the left hand column does not update.
[SimHub.log](https://github.com/SHWotever/SimHub/files/6353200/SimHub.log)

![Screenshot](https://user-images.githubusercontent.com/74878955/115605647-c223c500-a2b0-11eb-92d2-69187a732d6a.png)

**Comment by SHWotever** [comment] 2021-04-24 07:52
Hi ! I'm not sure to fully understand the issue, when you try to open the list to pick the correct value it does not opens ?

**Comment by rifer1** [comment] 2021-04-24 16:46
Good Afternoon,

The issue I've noticed the past few weeks is that when I change the last two parameters in the right hand column to FPS and frame time, the left hand column names did not change as they used to: they show GPU fan speed and frame rate, respectively.  Note the first five lines show matching names in the left and right hand column; it’s just the last two that don’t.

Thanks for the time, and thanks for a very impressive piece of software!

regards,
    R Rife

**Comment by SHWotever** [comment] 2022-08-14 07:04
Hi I close this as I could not reproduce it and nothing similar has been reported since.

**Closed by SHWotever** 2022-08-14 07:04 UTC
Labels: Waiting for infos
