### ISSUE TITLE
F1 2023, UDP relay

### ISSUE THREAD

**Issue by Ishan87** [SHWotever/SimHub#1337] opened 2023-06-17 13:48 UTC
**Describe the bug**
Port Forward to from Simhub to SRS does not work.

**Simhub version**
Using Latest version with F1 2023

**Comment by SHWotever** [comment] 2023-06-17 13:56
Hi ! I checked port forwarding with an UDP monitoring tool and it worked as intended, F1 23 is heavily based on the F1 22 structure and everything about port forwarding is the same. 

Since each game have it's own forwarding settings can you check that you got it enabled ? 
![image](https://github.com/SHWotever/SimHub/assets/2207331/78ec4547-a3ec-4f84-9321-f3058d46d233)


If it's the case can you join the screenshot of your settings (game, simhub port, simhub redirect, SRS configured port.

Nicolas

**Comment by SHWotever** [comment] 2023-06-17 14:49
Nb : I've read that SRS was not using the same port in F1 2023 than F1 2022, if you were using the same port to be redirected as F1 22 that would explain it.

**Comment by SHWotever** [comment] 2023-06-19 07:01
Hi I got the confirmation by another user that SRS have changed the port vs F1 22 and that udp redirect works fine when configured to right one. I close this ;)

**Closed by SHWotever** 2023-06-19 07:01 UTC
Labels: Waiting for infos
